### ISSUE TITLE
bad X server connection. DISPLAY=:120838741

### ISSUE THREAD

**Issue by soichih** [kitchell/app-AFQ_figures#2]
I ran this app on Brain-Life which landed on jetstream (matlab2) VM, and I saw following error message.

```
ERROR: In /home/ilan/minonda/conda-bld/work/VTK-6.3.0/Rendering/OpenGL/vtkXOpenGLRenderWindow.cxx, line 845
vtkXOpenGLRenderWindow (0x35b2fb0): bad X server connection. DISPLAY=:120838741. Aborting.
```

I think something went wrong with Xvfbwrapper..?

**Comment by kitchell** [comment]
Yeah that sounds like xfvbwrapper. Can you run it again? Remind me to look into this next week if I don't solve it this weekend

**Comment by kitchell** [comment]
I just ran a test and it ran on VM matlab2 with no problems

**Comment by soichih** [comment]
I've rerun several times but I couldn't recreate the issue -- they all finished successfully.
